python src/main.py --fixed_level -1.0 --fixed_length 0.30
python src/main.py --fixed_level -0.9 --fixed_length 0.30
python src/main.py --fixed_level -0.8 --fixed_length 0.30
python src/main.py --fixed_level -0.7 --fixed_length 0.30
python src/main.py --fixed_level -0.6 --fixed_length 0.30
python src/main.py --fixed_level -0.5 --fixed_length 0.30
python src/main.py --fixed_level -0.4 --fixed_length 0.30
python src/main.py --fixed_level -0.3 --fixed_length 0.30
python src/main.py --fixed_level -0.2 --fixed_length 0.30
python src/main.py --fixed_level -0.1 --fixed_length 0.30
python src/main.py --fixed_level 0.0 --fixed_length 0.30
python src/main.py --fixed_level 0.1 --fixed_length 0.30
python src/main.py --fixed_level 0.2 --fixed_length 0.30
python src/main.py --fixed_level 0.3 --fixed_length 0.30
python src/main.py --fixed_level 0.4 --fixed_length 0.30
python src/main.py --fixed_level 0.5 --fixed_length 0.30
python src/main.py --fixed_level 0.6 --fixed_length 0.30
python src/main.py --fixed_level 0.7 --fixed_length 0.30
python src/main.py --fixed_level 0.8 --fixed_length 0.30
python src/main.py --fixed_level 0.9 --fixed_length 0.30
python src/main.py --fixed_level 1.0 --fixed_length 0.30